### ISSUE TITLE
GP SPI W5500 Network Module

### ISSUE THREAD

**Issue by NonaSuomy** [atomic14/esp32-s3-pinouts#15]
I tried to use these pins for general SPI seems GPIO 9 didn't like to be used as a CS pin if switch that it works.
```yaml
ethernet:
  type: W5500
  clk_pin: GPIO05
  mosi_pin: GPIO04
  miso_pin: GPIO13
  cs_pin: GPIO09
  interrupt_pin: GPIO10
  reset_pin: GPIO12
 ```
 I then swapped them to
```yaml
ethernet:
  type: W5500
  clk_pin: GPIO42
  mosi_pin: GPIO44
  miso_pin: GPIO40
  cs_pin: GPIO39
  interrupt_pin: GPIO41
  reset_pin: GPIO43
```
and it worked.
  
 Any idea why? I think it was because of GPIO 9 and using some pins in the FSPI pin layout not in the order it wants
 
![image](https://github.com/atomic14/esp32-s3-pinouts/assets/1906575/d9e432f8-94d0-4d32-bf38-c3d14dc6694f)
